Fix a backwards compatibility issue with 1.0.0 create_simple_secret
For 1.1.0 we added some additional parameters to the
create_simple_secret function. The C++ code was not compatible anymore
with the 1.0.0 definitions of the SQL definition. So, if people wouldn't
upgrade their SQL part of the extension using:
```sql
ALTER EXTENSION pg_duckdb UPDATE
```
Then they would be getting an error like this:
```
ERROR:  XX000: (PGDuckDB/pgduckdb_create_simple_secret_cpp) Invalid Input Error: argument 9 is required
LOCATION:  pgduckdb_create_simple_secret_cpp, pgduckdb_options.cpp:145
```

This fixes that and adds a regression test to avoid breaking it in the
future.