Fix type assertions (#675)
Currently, the tests with assertions enabled fail with:

```
ERROR:  (PGDuckDB/Duckdb_ExecCustomScan_Cpp) INTERNAL Error: Assertion triggered in file "/Users/y/workspace/motherduck/pg_duckdb/third_party/duckdb/src/common/types/value.cpp" on line 1776: value.type().InternalType() == PhysicalType::LIST
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

This PR fixes it.