Make duckdb.install_extension('httpfs') not break the installation (#313)
Running the following (and then reconnecting because of #278)

```sql
SELECT duckdb.install_extension('httpfs');
```

Would completely break DuckDB functionality. You would always get the
following error:

```
ERROR:  XX000: (PGDuckDB/DuckDBQuery) Invalid Input Error: Initialization function "httpfs_init" from file "/home/jelte/.pgenv/pgsql/data/duckdb_extensions/v1.1.1/linux_amd64/httpfs.duckdb_extension" threw an exception: "Attempted to register an already registered secret type: 's3'"
```

This fixes that by essentially making
`duckdb.install_extension('httpfs')` a no-op.