Add missing member when initializing duckdb_methods (#442) (#443)
Without this there were compilation errors on RHEL8

```cpp
src/pgduckdb/pgduckdb_table_am.cpp:464: sorry, unimplemented: non-trivial designated initializers not supported
```

Fixes #442